config/routes.rb
Rails.application.routes.draw do

  resources :snippets

  root to: "snippets#new"

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base

  validates :title, :lang, :code, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def index
    @snippets = Snippet.all
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)

    if @snippet.save
      redirect_to @snippet, notice: "Snippet creado!"
    else 
      render :new
    end
  end

  def show
    @snippet = Snippet.find(params[:id])
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    redirect_to root_path, notice: "Snippet eliminado!"
  end

  private

  def snippet_params
    params.require(:snippet).permit(:title, :lang, :code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper

  def lexer_list
    supported_langs = Array.new

    ugly_list = Rouge::Lexer.all
    ugly_list.each do |lang|
      supported_langs << lang.to_s.split("::")[2].downcase
    end

    supported_langs - ["literatecoffeescript", "literatehaskell"]
  end

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
        data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Snippets</a>
    </div>
    <div class="navbar-collapse collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><a href="http://jam.net.ve">Web</a></li>
        <li><a href="http://jam.net.ve/cv">CV</a></li>
        <li><a href="http://blog.jam.net.ve">Blog</a></li>
      </ul>
    </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Paste</title>
  <%= stylesheet_link_tag    'application',
                              media: 'all',
                              'data-turbolinks-track' => true %>
                            
  <%= javascript_include_tag 'application',
                             'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navigation" %>
  <div class="container">
    <%= render "layouts/messages" %>
    <%= yield %>
  </div>
</body>
</html>

app/views/snippets/_form.html.erb
<div class="col-md-8">
<%= form_for :snippet, url: snippets_path,
                    html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @snippet.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited
    this note from being saved:</h2>
  <ul>
    <% @snippet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
  </ul>
</div>
  <% end %>

<div class="form-group">
<p>
<%= f.text_field :title, class: "form-control",
                         placeholder: "Titulo" %>
</p>

<p>
<%= f.select :lang, lexer_list, {}, { class: "form-control" } %>
</p>

<p>
<%= f.text_area :code, size: "60x12",
                       class: "form-control",
                       placeholder: "Codigo" %>
</p>

<p>
<%= f.submit "Guardar", class: "btn btn-primary" %>
</p>
</div>
<% end %>
<div>

app/views/snippets/index.html.erb
<h1>Lista de Snippets</h1>

<p><%= link_to "Nuevo Snippet", new_snippet_path %></p>

<table class="table table-striped table-bordered table-hover">
  <tr>
    <th>Titulo</th>
    <th>Lenguaje</th>
    <th colspan="2"></th>
  </tr>

  <% @snippets.each do |s| %>
    <tr>
    <td><%= s.title %></td>
    <td><%= s.lang.capitalize %></td>
    <td><%= link_to 'Mostrar', snippet_path(s) %></td>
    <td><%= link_to 'Eliminar', s, method: :delete,
      data: { confirm: "Seguro?" } %></td>
  </tr>
<% end %>
</table>

app/views/snippets/new.html.erb
<h1></h1>
<div>
  <%= render "form" %>
</div>
<%= link_to "Lista de Snippets", snippets_path %>

app/views/snippets/show.html.erb
<h1>Snippet</h1>

<p>
<%= link_to "Eliminar", @snipper, method: :delete,
        data: { confirm: "Seguro?" } %> |
<%= link_to "Inicio", root_path %>
</p>

<p>
<strong>Titulo:</strong>
<%= @snippet.title.capitalize %>
</p>

<p>
<strong>Lenguaje:</strong>
<%= @snippet.lang.capitalize %>
</p>

<p>
<strong>Codigo:</strong>
</p>
<p>
<%= raw Rouge.highlight @snippet.code, @snippet.lang, "html" %>
</p>